dbca-wa/gokart

- gokart/views/apps/sss.html
- gokart/views/base.html
- gokart/views/layers.html
- requirements.txt
Note: selection and highlighting is currently broken, need to fix
> addition of history query UI

- src/apps/sss.vue
- src/components/annotations.vue
- src/components/sss/tracking.vue
- annotations and tracking icons updated
- machinery filter added
- sector details text note now default and size of textarea adjusted accordingly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/10)
> minor adjustments to annotations and tracking panels

- src/apps/sss.vue
- src/components/annotations.vue
- src/components/layers.vue
- src/components/sss/tracking.vue
- remove leading line for text note
- device 'last seen' to short form
- open active layers tab on page load
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/11)
> minor UI fixes

- dist/release/static/css/style.css
- package.json
- src/apps/sss-tour.js
- src/apps/sss.js
- src/components/layers/active.vue
- src/components/map.vue
- src/vendor.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/14)
> Add multisearch widget

- src/components/annotations.vue
- src/components/layers/catalogue.vue
- src/components/sss/tracking.vue
- text notes font size and family now working
- catalogue preview less intrusive
- tracking search box filtering properly
- ensure tracking list loads properly on resource tracking panel load
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/13)
> text note annotations font, tracking and catalogue UI tweaks

- .gitignore
- dist/build_cordova.py
- dist/build_cordova.sh
- dist/www/js/patch.js
- gokart/__init__.py
- src/apps/sss.js
- src/vendor.js
- uwsgi.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/12)
> saveas feature for cordova app

- dist/release/static/css/style.css
- src/apps/sss.js
- src/components/map.vue
- src/components/sss/tracking.vue
- Mouse Position control added
- fix some minor css
- prepare system for change to vehicle Device model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/16)
> mouse position, css tweaks and tracking model adjustments

- gokart/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/21)
> Reserve the original file name with filename parameter in fetch uri which is generated and returned by saveas request

- gokart/__init__.py
- src/vendor.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/23)
> Use nginx as the reverse proxy for firewatch service.

- src/components/annotations.vue
- src/components/sss/tracking.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/24)
> Enable resource tracking layers if disabled when opening resource tracking panel.

- src/components/sss/tracking.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/27)
> tracking: changed to point at sss_admin for limited device admin access

- src/apps/sss.vue
- src/components/annotations.vue
- src/components/sss/tracking.vue
Disable query button if date rage or vehicle are empty; Verify date and time after inputting
Adjust canvas's dimension based on text note
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/26)
> Adjust canvas's dimension based on text note.

- src/components/annotations.vue
- src/components/layers/active.vue
- src/components/measure.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/56)
> #2311 hide/show active layers

- dist/release/static/css/style.css
- src/components/layers/active.vue
- src/components/layers/catalogue.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/70)
> layers: catalogue vue lock top rows in UI

- src/components/sss/bfrs.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/88)
> Increase the columns occupied by 'Restrict to viewport' toggle from 8  to 9 in bfrs module

- dist/release/static/js/uat.env.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/95)
> Add version into uat.env.js

- dist/release/static/js/prod.env.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/gokart/97)
> Missing wmsService in prod.env.js

- src/apps/sss-tour.js
- src/apps/sss.vue
- src/components/annotations.vue
- src/components/layers.vue
- src/components/settings.vue
- src/components/toolbox.vue
- src/components/weatheroutlook.vue
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/gokart/99)
> Open weather outlook customization panel when choose 'customized weather outlook' tool from toolbox

- dist/release/static/js/prod.env.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/gokart/101)
> Update production env file

- dist/release/static/js/prod.env.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/gokart/123)
> Update prod.env.js staticService to use dbca
